serviceList:
  - name: Cinema
    type: system
    description: simple cinema system
    config:
      # this endpoint is one of the parameter, used by SKILL, not requesting skill
      - context: jenkins
        properties:
          - name: Api.endpoint
            value: http://soselab.asuscomm.com:10000
          - name: User.username
            value: linux
          - name: Api.accessToken
            value: 11eb26ac2812dda2527594fc7a423a98fd
      - context: eureka
        properties:
          - name: User.username
            value: name
    service:
      - name: Ordering
        type: service
        description: ordering service
        config:
          - context: jenkins
            properties:
              - name: Api.endpoint
                value: http://soselab.asuscomm.com:10000
      #              - name: User.username
      #                value: linux
      #              - name: Api.accessToken
      #                value: 11eb26ac2812dda2527594fc7a423a98fd
      #          endpoint: http://soselab.asuscomm.com:10000
      #          username: linux
      #          accessToken: 11eb26ac2812dda2527594fc7a423a98fd
      - name: Payment
        type: service
        description: payment service
      - name: Notification
        type: service
        description: notification service
  - name: Fake-System
    type: system
    description: fake system
    config:
      - context: general
        properties:
          - name: Api.endpoint
            value: url
          - name: User.username
            value: me
          - name: Api.accessToken
            value: toKen
    #      endpoint: url
    #      username: me
    #      accessToken: toKen
    service:
      - name: FakeOne
        type: service
        description: try to use get method
        config:
          - context: general
            properties:
              - name: User.username
                value: fake one
      #          username: fake one
      - name: FakeTwo
        type: service
        description: fake service
        config:
          - context: general
            properties:
              - name: User.username
                value: fake two
  - name: DemoOnly
    type: system
    description: pseudo system
    service:
      - name: Member
        type: service
        description: member service
      - name: Game
        type: service
        description: game service